server:
  port: 8081

spring:
  application:
    name: auth-service
  config:
    import: "optional:configserver:http://localhost:8888/"
  datasource:
    url: jdbc:mysql://localhost:3306/renstation_auth?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      host: localhost
      port: 6379
  flyway:
    enabled: true
    baseline-on-migrate: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  private-key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDhC...
    -----END PRIVATE KEY-----
  public-key: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4Qg...
    -----END PUBLIC KEY-----

logging:
  level:
    com.renstation.auth: DEBUG
