server:
  port: 8090

spring:
  application:
    name: admin-service
  config:
    import: "optional:configserver:http://localhost:8888/"
  datasource:
    url: jdbc:mysql://localhost:3306/renstation_admin?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    com.renstation.admin: DEBUG
