server:
  port: 8761

spring:
  application:
    name: discovery-server
  config:
    import: "optional:configserver:http://localhost:8888/"
  lifecycle:
    timeout-per-shutdown-phase: 20s

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: false # Recommended to disable in dev/small clusters

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, env
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

logging:
  level:
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO
