spring:
  config:
    activate:
      on-profile: prod
cors:
  allowed-origins: "https://renstation.com,https://www.renstation.com"
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://discovery-server:8761/eureka/}
