server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: native # Default to native for local development

management:
  endpoints:
    web:
      exposure:
        include: health, info, env, refresh
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.config.server: INFO
